export const translations = {
    fr: {
        home: 'Accueil',
        projects: 'Projets',
        participate: 'Participez',
        news: 'Actualités',
        contact: 'Contact',
        donate: 'Faire un don',
        volunteer: 'Devenir bénévole',
        joinMission: 'Rejoignez notre mission',
        heroTitle: 'Ensemble, rallumons l\'espoir – construisons un avenir digne pour nos communautés',
        whoWeAre: 'Qui sommes-nous ?',
        weAreText: 'CTLCO Foundation est une organisation congolaise à but non lucratif qui agit au cœur des communautés défavorisées. Depuis Kinshasa, Goma, Kolwezi et Lubumbashi, nous soutenons l\'éducation des enfants, la dignité des femmes, la santé des personnes âgées et le développement durable des familles vulnérables.',
        education: 'Éducation',
        health: 'Santé & Bien-être',
        activities: 'Activités parascolaires',
        community: 'Développement communautaire',
        testimonials: 'Témoignages',
        davidQuote: '"Grâce à la fondation, j\'ai pu retourner à l\'école et rêver à un avenir meilleur."',
        davidName: 'David, 13 ans',
        aishaQuote: '"J\'ai appris à créer un petit commerce qui nourrit ma famille."',
        aishaName: 'Maman Aisha, bénéficiaire',
        howToHelp: 'Comment aider ?',
        donateText: 'Faire un don',
        donateDesc: 'Paiement sécurisé (Mobile Money, PayPal, Carte bancaire)',
        volunteerText: 'Devenir bénévolе',
        volunteerDesc: 'Formulaire rapide',
        supportProject: 'Soutenir un projet',
        supportDesc: 'Choisir un projet précis',
        recentNews: 'Actualités récentes',
        news1: 'Distribution de kits scolaires à Goma – 250 élèves bénéficiaires',
        news2: 'Clubs de lecture lancés à Kolwezi – 3 écoles déjà impliquées',
        news3: 'Campagne de dépistage gratuit à Kinshasa – 120 femmes assistées',
        seeAllNews: 'Voir toutes nos actualités',
        locations: 'Villes d\'implantation',
        quickLinks: 'Liens rapides',
        social: 'Réseaux sociaux',
        newsletter: 'Recevez nos nouvelles et restez connectés à nos actions',
        subscribe: 'S\'abonner',
        legal: 'Mentions légales',
        privacy: 'Politique de confidentialité',
        impactStudents: 'enfants scolarisés',
        impactWomen: 'femmes accompagnées',
        impactElderly: 'personnes âgées soutenues',
        impactProjects: 'projets communautaires réalisés'
    },
    en: {
        home: 'Home',
        projects: 'Projects',
        participate: 'Participate',
        news: 'News',
        contact: 'Contact',
        donate: 'Donate',
        volunteer: 'Volunteer',
        joinMission: 'Join our mission',
        heroTitle: 'Together, reignite hope – build a dignified future for our communities',
        whoWeAre: 'Who we are?',
        weAreText: 'CTLCO Foundation is a Congolese non-profit organization acting at the heart of disadvantaged communities. From Kinshasa, Goma, Kolwezi and Lubumbashi, we support children\'s education, women\'s dignity, elderly health and sustainable development of vulnerable families.',
        education: 'Education',
        health: 'Health & Well-being',
        activities: 'Extracurricular activities',
        community: 'Community development',
        testimonials: 'Testimonials',
        davidQuote: '"Thanks to the foundation, I was able to return to school and dream of a better future."',
        davidName: 'David, 13 years old',
        aishaQuote: '"I learned how to create a small business that feeds my family."',
        aishaName: 'Mother Aisha, beneficiary',
        howToHelp: 'How to help?',
        donateText: 'Donate',
        donateDesc: 'Secure payment (Mobile Money, PayPal, Credit Card)',
        volunteerText: 'Volunteer',
        volunteerDesc: 'Quick form',
        supportProject: 'Support a project',
        supportDesc: 'Choose a specific project',
        recentNews: 'Recent news',
        news1: 'Distribution of school kits in Goma – 250 beneficiary students',
        news2: 'Reading clubs launched in Kolwezi – 3 schools already involved',
        news3: 'Free screening campaign in Kinshasa – 120 women assisted',
        seeAllNews: 'See all our news',
        locations: 'Locations',
        quickLinks: 'Quick links',
        social: 'Social media',
        newsletter: 'Receive our news and stay connected to our actions',
        subscribe: 'Subscribe',
        legal: 'Legal notice',
        privacy: 'Privacy policy',
        impactStudents: 'children educated',
        impactWomen: 'women supported',
        impactElderly: 'elderly people supported',
        impactProjects: 'community projects completed'
    }
};